{ pkgs, config, ... }:
{ 
  # Create symlinks for my dotfiles to ~${config.username}
  system.activationScripts.createDotConfigSymlinks = {
    text = ''
      # Get the names of config directories in dot-files
      config_directories=$(find ${config.nixOSConfigPath}/common/dot-files/ -maxdepth 1 -mindepth 1 -type d -printf "%f\n")

      for dir_name in $config_directories; do
        target_path=~${config.username}/.config/$dir_name 

        # If the target isn't a symlink i.e. not generated by NixOS, save it just in case.
        if [ ! -L $target_path ]; then
          mv $target_path $target_path.bak
        else
        # Else remove the already existing symlink to refresh it
          echo "Deleting symlink at $target_path"
          rm $target_path
        fi

        source=${config.nixOSConfigPath}/common/dot-files/$dir_name

        echo "Creating a symlink from $source to $target_path"
        ln -s $source $target_path
      done
    '';
  };
}
